[project]
name = 'stackflow'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.reservoir]
path = 'contracts/reservoir.clar'
clarity_version = 4
epoch = "3.3"

[contracts.stackflow]
path = 'contracts/stackflow.clar'
clarity_version = 4
epoch = "3.3"

[contracts.stackflow-token]
path = 'contracts/stackflow-token.clar'
clarity_version = 4
epoch = "3.3"

[contracts.test-token]
path = 'contracts/test-token.clar'
clarity_version = 4
epoch = "3.3"

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
